apiVersion: v1
kind: Service
metadata:
  namespace: fluxim
  name: example-app
  labels:
    app: example-app
spec:
  type: ClusterIP
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000