apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app
  namespace: fluxim
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/VLXMDE/fluxim
  secretRef:
    name: example-app-github
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app
  namespace: default
spec:
  interval: 15m
  path: "./example-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app