apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: example-app
  namespace: fluxim
spec:
  imageRepositoryRef:
    name: example-app
  policy:
    semver:
      range: 0.0.x