apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: example-app
  namespace: fluxim
spec:
  image: docker.io/demvx007/example-app
  interval: 1m0s
  secretRef:
    name: dockerhub-credential